### ISSUE TITLE
Make new_auth use a String

### ISSUE THREAD

**Issue by adri326** [jaredforth/roy#1]
Some applications require a token to be first obtained through some login system and then be used as authentication.
This means that the token is usually stored as some sort of `String`.

However, `new_auth` requires such token to be of type `&'static str`. Converting a `String` into a `&'static str` requires leaking the string or using unsafes.

My proposal is to swap the `&'static str` out for a `String` (akin to the entirety of the remaining code base), and use `reqwest::header::HeaderValue::from_str` instead.
The only downside to this is that it would require you to add a bit of logic to handle the return value of that `from_str` function.

**Comment by jaredforth** [comment]
Thanks for your feedback @adri326. I think this is a good idea and I will work on implementation.
